apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  labels:
    name: eureka-server
spec:
  type: LoadBalancer
  ports:
  - port: 8761
    targetPort: 8761
  selector:
    name: eureka-server