apiVersion: v1
kind: ReplicationController
metadata:
  name: webapp
  labels:
    name: webapp
spec:
  replicas: 1
  selector:
    name: webapp
  template:
    metadata:
      labels:
        name: webapp
    spec:
      containers:
      - name: webapp
        image: kanicz/microservices-webapp
        ports:
        - containerPort: 8080
        env:
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: http://eureka-server.default:8761/eureka/
        - name: EUREKA_INSTANCE_HOSTNAME
          value: webapp.default
        - name: SPRING_CLOUD_CONFIG_DISCOVERY_ENABLED
          value: "true"
        - name: SPRING_CLOUD_CONFIG_DISCOVERY_SERVICEID
          value: config-server